### ISSUE TITLE
InvalidForegroundServiceTypeException: Starting FGS with type none 

### ISSUE THREAD

**Issue by dennischen** [colaorange/daily-money-one-doc#66]
應用程式版本：1.5.0 (48)
OS 版本： android14
型號：Galaxy A52s 5G
          Fatal Exception: android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{4723947 10019:com.colaorange.dailymoneyone/u0a286} targetSDK=34 has been prohibited
       at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
       at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
       at android.os.Parcel.readParcelable(Parcel.java:4864)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
       at android.os.Parcel.createException(Parcel.java:3053)
       at android.os.Parcel.readException(Parcel.java:3036)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
       at android.app.Service.startForeground(Service.java:862)
       at androidx.work.impl.foreground.SystemForegroundService$Api31Impl.startForeground(SystemForegroundService.java:193)
       at androidx.work.impl.foreground.SystemForegroundService$1.run(SystemForegroundService.java:129)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by dennischen** [comment]
I did use any service in 1.5.0, it is possibly been to used by some other 3rd react lib

**Comment by dennischen** [comment]
since 14+, when creatking ForegroundInfo, needs to provide service type
